- hosts: all
  tasks:
    - name: data
      shell: date
    - name: whoami
      shell: whoami
    - name: ip
      shell: ip addr > /tmp/ansible.txt
    - name: df
      shell: df -h >>/tmp/ansible.txt
    - name: free
      shell: free -h >>/tmp/ansible.txt
